{{- /* ---- Proxy Service ---- */}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "edgequota.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "edgequota.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  {{- with .Values.service.clusterIP }}
  clusterIP: {{ . }}
  {{- end }}
  {{- with .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- with .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ . }}
  {{- end }}
  {{- if .Values.service.ipFamilyPolicy }}
  ipFamilyPolicy: {{ .Values.service.ipFamilyPolicy }}
  {{- end }}
  {{- with .Values.service.ipFamilies }}
  ipFamilies:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  ports:
    - name: {{ include "edgequota.servicePortName" . }}
      port: {{ include "edgequota.servicePort" . }}
      targetPort: proxy
      protocol: TCP
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
    {{- if and .Values.edgequota.server.tls.enabled .Values.edgequota.server.tls.http3Enabled }}
    - name: https-udp
      port: 443
      targetPort: proxy-udp
      protocol: UDP
    {{- end }}
  selector:
    {{- include "edgequota.selectorLabels" . | nindent 4 }}
---
{{- /* ---- Admin Service (always ClusterIP) ---- */}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "edgequota.fullname" . }}-admin
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "edgequota.labels" . | nindent 4 }}
  {{- with .Values.service.adminAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
    - name: admin
      port: {{ include "edgequota.adminPort" . }}
      targetPort: admin
      protocol: TCP
  selector:
    {{- include "edgequota.selectorLabels" . | nindent 4 }}
